# use nodejs alpine image as base image
FROM node:22-alpine
# set the working directory to /app 
WORKDIR /app
# copy package.json and lock.json files
COPY package*.json ./
RUN npm install
COPY . .
# expose port 3000
EXPOSE 3000
CMD [ "npm", "start" ]