name: posthog-container app Manual Deployment

# When this action will be executed
on: workflow_dispatch

jobs:
  # Job run image.
  build:
    runs-on: ubuntu-latest

    # Steps that need to happen in this job run.
    steps:
      # Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password:
            ${{ secrets.DOCKER_PASSWORD }}

            # Build the Docker image
      - name: Build Docker image
        run: |
          docker build \
            --build-arg KINDE_CLIENT_ID="fd7406b8-cd0f-40d8-806f-e7017caa410" \
            --build-arg KINDE_CLIENT_SECRET="fd731090-99a1-4dc0-bef9-bae2c1b952b1" \
            --build-arg NEXT_PUBLIC_APP_URL="https://charanzencon.graysmoke-418af36c.centralindia.azurecontainerapps.io" \
            -t charanposthog:latest .

      # tag the Docker image
      - name: Tag Docker image
        run: docker tag charanposthog:latest ${{ secrets.DOCKER_USERNAME }}/charanposthog:${{ github.sha }}

        # Push the Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/charanposthog:${{ github.sha }}

        # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          # use Azure credentials for the login
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Deploy to Azure Container Apps
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ vars.CONTAINER_APP_NAME }}
          resourceGroup: Charansai
          imageToDeploy: docker.io/${{ secrets.DOCKER_USERNAME }}/charanposthog:${{ github.sha }}
          containerAppEnvironment: charanzenpoc