name: posthog-container app Manual Deployment

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg KINDE_CLIENT_ID="fd7406b8-cd0f-40d8-806f-e7017caa410" \
            --build-arg KINDE_CLIENT_SECRET="fd731090-99a1-4dc0-bef9-bae2c1b952b1" \
            --build-arg NEXT_PUBLIC_APP_URL="https://charanzencon.graysmoke-418af36c.centralindia.azurecontainerapps.io" \
            -t charanposthog:latest -f Dockerfile.prod .

      - name: Tag Docker image
        run: docker tag charanposthog:latest ${{ env.DOCKER_USERNAME }}/charanposthog:${{ github.sha }}

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_USERNAME }}/charanposthog:${{ github.sha }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ vars.CONTAINER_APP_NAME }}
          resourceGroup: Charansai
          imageToDeploy: docker.io/${{ env.DOCKER_USERNAME }}/charanposthog:${{ github.sha }}
          containerAppEnvironment: charanzenpoc
