name: posthog-container app Manual Deployment

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    env:
      GREEN_REVISION: green-${{ github.run_number }}-${{ github.run_attempt }}
      BLUE_REVISION: blue-${{ github.run_number }}-${{ github.run_attempt }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Print the run number
        run: |
            echo "This is GitHub Actions run number ${{ github.run_number }}"
            echo "This is GitHub Actions run number ${{ github.run_attempt }}"

      # - name: Build Docker image
      #   run: |
      #     docker build \
      #       --build-arg KINDE_CLIENT_ID="fd7406b8-cd0f-40d8-806f-e7017caa410" \
      #       --build-arg KINDE_CLIENT_SECRET="fd731090-99a1-4dc0-bef9-bae2c1b952b1" \
      #       --build-arg NEXT_PUBLIC_APP_URL="https://charanzencon.graysmoke-418af36c.centralindia.azurecontainerapps.io" \
      #       -t multistage1:latest -f Dockerfile.prod .

      # - name: Tag Docker image
      #   run: docker tag multistage1:latest ${{ vars.DOCKER_USERNAME }}/multistage1:${{ github.sha }}

      # - name: Push Docker image
      #   run: docker push ${{ vars.DOCKER_USERNAME }}/multistage1:${{ github.sha }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: get the current reversion
        run : |
          az containerapp revision list --name charanzenconapp-volumes-test1 --resource-group ZenPOC --query "[?properties.active].{ReversionName:name}[0]" -o tsv > current-revision.txt
          echo "Current revision is $(cat current-revision.txt)"
          az containerapp revision copy --name charanzenconapp-volumes-test1 --resource-group ZenPOC --resource-group ZenPOC --revision-sufix "${{ env.BlUE_REVISION }}"
          echo "Blue revision is $(cat current-revision.txt) --revision-sufix ${{ env.BLUE_REVISION }}"

      # - name: Deploy to Azure Container Apps
      #   uses: azure/container-apps-deploy-action@v1
      #   with:
      #     resourceGroup: ZenPOC
      #     imageToDeploy: docker.io/${{ vars.DOCKER_USERNAME }}/multistage1:${{ github.sha }}
      #     containerAppEnvironment: charanzenpoc
      #     containerAppName: charanzenconapp-volumes-test1

